type Mutation {
  createColor(data: ColorInput!): Color!

  updateColor(id: ID!, data: ColorInput!): Color

  partialUpdateColor(id: ID!, data: PartialUpdateColorInput!): Color

  deleteColor(id: ID!): Color
}
