type Color {
  _id: ID! @auth(requires: ADMIN)
  name: ID!
  color: String!
  palette: Palette!
  _ts: Long!
}

# Allow manipulating the relationship between the types 'Color' and 'Palette' using the field 'Color.palette'.
input ColorPaletteRelation {
  # Create a document of type 'Palette' and associate it with the current document.
  create: PaletteInput

  # Connect a document of type 'Palette' with the current document using its ID.
  connect: ID
}

# 'Color' input values
input ColorInput {
  name: ID!
  color: String!
  palette: ColorPaletteRelation
}

# 'Color' input values
input PartialUpdateColorInput {
  name: ID
  color: String
  palette: ColorPaletteRelation
}
