type Mutation {
  createPalette(data: PaletteInput!): Palette!

  updatePalette(id: ID!, data: PaletteInput!): Palette

  partialUpdatePalette(id: ID!, data: PartialUpdatePaletteInput!): Palette

  deletePalette(id: ID!): Palette
}
